# spring server port configurations :
server:
  port: 8086

spring:
  boot:
    name: Hi there, it's organization service :)

# data source configurations :
  dataSource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: 1234

# jpa configurations :
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

# eureka server configurations :
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/






